# Grading process


All assignments should be submitted in pairs. Only one member of a pair should submit the assignment. If you don't have a pair yet, you can submit individually (this assignment only). The submission notebook will be automatically validated with Papermill.

Papermill will inject new cell after each cell tagged as `parameters` (see `View > Cell toolbar > Tags`). Notebook will be executed from top to bottom in a linear order.

Please, **fill `STUDENT` variable with your name**, so that we can collect the results automatically. Please, do not change `parameters` (specifically, **do not change `TEST` variable**) and `validation` cells for grader to work correctly. You can, though, use the following clauses to wrap your code outside of `solution` cells:

```python
if not TEST:
    <some code >
```

Each problem contains specific validation details. You need to fill each cell tagged `solution` with your code. Note, that solution function must be self-contained, i.e. it must not use any state from the notebook itself.

Different problems result in different number of points. All problems in the basic section give 1 point, while all problems in intermediate section give 2 points. Total number of points are then divided by maximum number of points (11 in this assignment) and multiplied by 100 to get your final grade (0-100).

You may find the following NumPy functions useful:

- reduction functions: `np.mean`, `np.std`, `np.max`,
- array creation functions: `np.zeros`, `np.arange`, `np.linspace`,
- element-wise functions: `np.sin`, `np.isfinite`, `np.clip`,
- other functions: `np.argmax`, `np.unique`, `np.column_stack`.

In [1]:
import numpy as np

In [2]:
STUDENT = "Amit Zulan, Ophir Turetz" # use your name here

In [3]:
ASSIGNMENT = 1
TEST = False

In [4]:
if TEST:
    import solutions
    total_grade = 0
    MAX_POINTS = 11

# Basic arrays

Problems 1, 2 and 3 cover the correct usage of `np.arange` (or `np.linspace` for that matter), basic masking and vectorized functions (like calculating `sin` of each element of an array in a vectorized manner).

### 1. Calculate $\sin(x)$ for $0\leq x < 2\pi$ with a step of $0.1$.

You need to implement a function, which calculates the required array. The exact values of $x$ are $[0, 0.1, 0.2,\ldots,6.2]$.

Result must be **1-dimensional**, and **will be tested against precomputed values**.

Note, that `numpy` provides [constants](https://docs.scipy.org/doc/numpy-1.15.0/reference/constants.html), you can take $\pi$ from there.

In [5]:
def sin_basic():
    # your code goes here
    x = np.arange(0, 2*np.pi, 0.1)
    return np.sin(x)

In [6]:
PROBLEM_ID = 1

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, sin_basic)

In [7]:
if not TEST:
  print(np.arange(0,2*np.pi,0.1))
  print(sin_basic())
  print(sin_basic().shape)
  print(sin_basic().ndim)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2]
[ 0.          0.09983342  0.19866933  0.29552021  0.38941834  0.47942554
  0.56464247  0.64421769  0.71735609  0.78332691  0.84147098  0.89120736
  0.93203909  0.96355819  0.98544973  0.99749499  0.9995736   0.99166481
  0.97384763  0.94630009  0.90929743  0.86320937  0.8084964   0.74570521
  0.67546318  0.59847214  0.51550137  0.42737988  0.33498815  0.23924933
  0.14112001  0.04158066 -0.05837414 -0.15774569 -0.2555411  -0.35078323
 -0.44252044 -0.52983614 -0.61185789 -0.68776616 -0.7568025  -0.81827711
 -0.87157577 -0.91616594 -0.95160207 -0.97753012 -0.993691   -0.99992326
 -0.99616461 -0.98245261 -0.95892427 -0.92581468 -0.88345466 -0.83226744
 -0.77276449 -0.70554033 -0.63126664 -0.55068554 -0.46460218 -0.37387666
 -0.2794155  

### 2. Create a function, which calculates $n$ values of $\sin(x)$ for $0\leq x \leq 2\pi$.

Both $0$ and $2\pi$ must be included and $x$ values must be equidistant. Result must be **1-dimensional**, and **will be tested against three random values for $10 \leq n < 100 $**.

Example values to be calculated for $n=3$ are:

$$\sin(0),\sin(\pi),\sin(2\pi),$$

while for $n=5$ we have

$$\sin(0),\sin(\pi/2),\sin(\pi),\sin(3\pi/2), \sin(2\pi)$$.


In [8]:
def sin_enumerated(n):
    # your code goes here
    x = np.linspace(0, 2*np.pi, n)
    return np.sin(x)

In [9]:
PROBLEM_ID = 2

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, sin_enumerated)

In [10]:
if not TEST:
  print(np.linspace(0, 2*np.pi, 3))
  print(np.linspace(0, 2*np.pi, 5))
  print(sin_enumerated(3))
  print(sin_enumerated(3).shape)
  print(sin_enumerated(3).ndim)

[0.         3.14159265 6.28318531]
[0.         1.57079633 3.14159265 4.71238898 6.28318531]
[ 0.0000000e+00  1.2246468e-16 -2.4492936e-16]
(3,)
1


### 3. Create a function, which calculates $n$ values of truncated $\sin(x)$ for $0\leq x \leq 2\pi$.

Truncated $\sin(x)$ is defined as the following:

$$
\sin_{trunc}(x) =
\left\{
\begin{array}{l}
\sin(x), \sin(x)\geq 0, \\
0, \sin(x) < 0.
\end{array}\right.
$$

Otherwise, the requirements are the same as in Problem 2.

In [11]:
def sin_truncated(n):
    # your code goes here
    output = sin_enumerated(n)
    output[output < 0] = 0
    return output

In [12]:
PROBLEM_ID = 3

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, sin_truncated)

In [13]:
if not TEST:
  print(sin_enumerated(5))
  print(sin_truncated(5))
  print(sin_truncated(5).shape)
  print(sin_truncated(5).ndim)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
[0.0000000e+00 1.0000000e+00 1.2246468e-16 0.0000000e+00 0.0000000e+00]
(5,)
1


### 4. Statistics on multi-dimensional arrays.

Given a 3-dimensional array `arr`, calculate mean and standard deviation along dimensions $(1,2)$.

For a $N\times M \times K$ array `arr`, result must be a **2-dimensional** array of shape $N\times 2$, with column `0` containing mean values and column `1` containing standard deviations. For example, $(0,0)$ element of the resulting array contains mean of `arr[0]`, while $(1,1)$ contains standard deviation of `arr[1]`.

Your solution **will be tested against three random combinations of input array dimensions ($10 \leq n < 100 $)**. Array values will be drawn from the standard normal distribution (`np.random.randn`).

**Hint:** this problem may need to use some universal functions and array combination routines.

In [14]:
def array_stats(arr):
    # your code goes here
    means = arr.mean(axis = (1,2))
    stds = arr.std(axis = (1,2))
    return np.vstack([means, stds]).T

In [15]:
PROBLEM_ID = 4

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, array_stats)

In [16]:
if not TEST:
  arr = np.ones((5,7,13))
  print(array_stats(arr))
  print(array_stats(arr).shape)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
(5, 2)


### 5. Class prediction.

Given a probability matrix, you need to calculate the exact class, i.e. determine, which probability is the highest for each example. For example, for the following array

$$
\left(
\begin{array}{ccc}
0.3 && 0.6 && 0.1 \\
0.8 && 0.05 && 0.15
\end{array}
\right)
$$

the result must be

$$
\left(
\begin{array}{c}
1 \\
0
\end{array}
\right)
$$

Each row represents an example, and each column represent a probability for corresponding class. For example, element `(0, 1)` represents the probability of example `0` being of class `1`.

Note, that result must be **2-dimensional**, such that input array of shape $(N, M)$ is transformed into output array of shape $(N,1)$. Result **will be tested against three random combinations of input array dimensions ($10 \leq n < 100 $)**. Input array elements are drawn from the standard normal distribution with $\texttt{softmax}$ applied on top.

#### $\texttt{softmax}$

$\texttt{softmax}$ is used to represent **probabilities** and is often used as an activation function in neural networks for multi-class classification.

$\texttt{softmax}$ activation for a vector is defined as the following:

$$
\texttt{softmax} (x_i) = \frac{e^{x_i}}{\sum_i e^{x_i}}.
$$

Correspondingly, a `2D` array is transformed as the following:

$$
\texttt{softmax} (x_{ij}) = \frac{e^{x_{ij}}}{\sum_j e^{x_{ij}}}.
$$



For example, an input array

$$
\left(
\begin{array}{cc}
1 && 6 \\
4 && 5
\end{array}
\right)
$$

results in the following $\texttt{softmax}$ activation:

$$
\left(
\begin{array}{cc}
\frac{e^1}{e^1 + e^6} && \frac{e^6}{e^1 + e^6} \\
\frac{e^4}{e^4 + e^5} && \frac{e^5}{e^4 + e^5}
\end{array}
\right)
$$


Result may be treated as **probabilistic predictions** of some classification model, as values sum to `1` for each row.

In [17]:
def predict(arr):
    # your code goes here
    return arr.argmax(axis = 1, keepdims=True)

In [18]:
PROBLEM_ID = 5

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, predict)

In [19]:
if not TEST:
  arr = np.array([[0.3 , 0.6 , 0.1],
                  [0.8 , 0.05 , 0.15]])
  print(predict(arr))
  print(predict(arr).shape)

[[1]
 [0]]
(2, 1)


# Intermediate arrays

### 6. One-hot encoding.

Given 1-dimensional array of class labels, construct it's one-hot encoded transformation. One-hot encoding of an array of shape $(N,)$ is defined as an array of shape $(N,L)$, such that $e_{ij}$ is $1$ if $i$-th example belongs to class $j$ and $0$ otherwise. $L$ is the number of classes.

For example, array $(1,0,3,1,1,1,0)$ is transformed to

$$
\left(
\begin{array}{cccc}
0 && 1 && 0 && 0\\
1 && 0 && 0 && 0\\
0 && 0 && 0 && 1\\
0 && 1 && 0 && 0\\
0 && 1 && 0 && 0\\
0 && 1 && 0 && 0\\
1 && 0 && 0 && 0
\end{array}
\right)
$$

Class labels are consequtive integers, hence $L$ corresponds to the largest integer value in the input array. Note, that in the example above we do not have `2` in the input although the result is still $7\times 4$ with column `2` containing all `0`'s.

This function will be tested against three input arrays of random shape $(n,)$ ($10 \leq n < 100 $) filled with random integers.

**Hint:** you may need some fancy indexing.

In [20]:
def onehot(labels):
    # your code goes here
    N = labels.size
    L = labels.max()

    output = np.zeros((N, L + 1))

    output[np.arange(N), labels] = 1

    return output

In [21]:
PROBLEM_ID = 6

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, onehot)

In [22]:
if not TEST:
  print(onehot(np.array([1,0,3,1,1,1,0])))
  print(onehot(np.array([1,0,3,1,1,1,0])).shape)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
(7, 4)


### 7. Fixing missing values.

Given an array, which contains some $NaN$s (not-a-number, represented as `np.nan`), positive and negative infinities (represented as `np.inf`), contruct a "repaired" version of that array. All missing or broken values must be replaced by average of valid elements of an array.

For example, array $(0., np.nan, 2., np.inf)$ must be transformed to $(0., 1., 2., 1.)$.

Input arrays will be drawn from standard normal distribution, with small fraction of values transformed to either `np.nan`, `np.inf` or `-np.inf`.

**Hint:** you will need some masking to achieve the goal, as well as `np.isnan` and `np.isinf`.

In [48]:
def fix(arr):
    # your code goes here
    invalids_mask = np.isnan(arr) | np.isinf(arr)
    valids_mean = arr[~invalids_mask].mean()

    repaired_arr = arr.copy()
    repaired_arr[invalids_mask] = valids_mean

    return repaired_arr

In [49]:
PROBLEM_ID = 7

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, fix)

In [50]:
if not TEST:
  print(fix(np.array([0., np.nan, 2., np.inf])))

[0. 1. 2. 1.]


### 8. Calculate class distribution.

Given 1-dimensional array of class labels, calculate occurrence of each class.

For example, array $(1,0,3,1,1,1,0)$ is transformed to $(2/7, 4/7, 0, 1/7)$. Class labels are consequtive integers, in the same way as in Problem 7 (note, that class `2` is not present in the input array, but it's occurence, although `0`, is included in the output).

Note the ordering and consider using one-hot representation to calculate class counts.

In [ ]:
def class_freq(labels):
    # your code goes here
    pass

In [ ]:
PROBLEM_ID = 8

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, class_freq)

### 9. Check for diagonal matrix.

In linear algebra, a **diagonal matrix** is a matrix in which the entries outside the main diagonal are all zero; the term usually refers to square matrices.

Implement a boolean function that gets a numpy array/matrix and returns True if it's diagonal and False if it isn't.

Non-square matrices should always return False. Don't use `numpy.diagonal` and `numpy.diag`

In [ ]:
def diagonal(matrix):
    # your code goes here
    pass

In [ ]:
PROBLEM_ID = 9

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, diagonal)

### 10. Efficient Matrix power function.

Implement an efficient matrix power function. The function receives a square diagonizable matrix and a power and returns that matrix raised to that power.

You need to implement it from scratch using eigenvectors and diagonal matrix power.
You can refer to an example is in Linear Algebra notebook.\
Remember that any diagonizable matrix (a matrix that has a full set of linearly independent eigenvectors) can be decomposed as:
    
$$
s = VEV^{-1}
$$

where $E$ is a diagonal matrix (with eigenvalues on main diagonal), and $V$ is a matrix where columns are eigenvectors.

Diagonal mareix $E$ can be easily raised into any power, by raising it's individual elements into that power.

Don't implement it by multiplying the matrix by itself many times or by using `numpy.linalg.matrix_power`

In [ ]:
def mat_power(matrix, power):
    # your code goes here
    pass

In [ ]:
PROBLEM_ID = 10

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, mat_power)

# Your grade

In [ ]:
if TEST:
    print(f"{STUDENT}: {int(100 * total_grade / MAX_POINTS)}")